from datetime import datetime
from typing import Any, Protocol
from uuid import UUID

from app.modules.platform.contracts.events import EventEnvelope


class InventoryRepository(Protocol):
    # --- Warehouses ---
    async def get_warehouse(self, tenant_id: UUID, resource_id: UUID, *, lock: bool = False) -> Any | None: ...
    async def get_warehouse_by_code(self, tenant_id: UUID, code: str) -> Any | None: ...
    async def list_warehouses(
        self, tenant_id: UUID, *, limit: int, cursor: tuple[datetime, UUID] | None, status: str | None = None
    ) -> tuple[list[Any], bool]: ...
    async def create_warehouse(self, tenant_id: UUID, actor_id: UUID, data: dict[str, Any]) -> Any: ...

    # --- Locations ---
    async def get_location(self, tenant_id: UUID, resource_id: UUID, *, lock: bool = False) -> Any | None: ...
    async def list_locations(
        self, tenant_id: UUID, *, limit: int, cursor: tuple[datetime, UUID] | None, warehouse_id: UUID | None = None
    ) -> tuple[list[Any], bool]: ...
    async def create_location(self, tenant_id: UUID, actor_id: UUID, data: dict[str, Any]) -> Any: ...

    # --- Stock levels ---
    async def get_stock_level(self, tenant_id: UUID, resource_id: UUID, *, lock: bool = False) -> Any | None: ...
    async def get_stock_level_by_location_variant(
        self, tenant_id: UUID, location_id: UUID, variant_id: UUID, *, lock: bool = False
    ) -> Any | None: ...
    async def get_or_create_stock_level(
        self, tenant_id: UUID, actor_id: UUID, location_id: UUID, variant_id: UUID
    ) -> Any: ...
    async def list_stock_levels(
        self,
        tenant_id: UUID,
        *,
        limit: int,
        cursor: tuple[datetime, UUID] | None,
        variant_id: UUID | None = None,
        location_id: UUID | None = None,
    ) -> tuple[list[Any], bool]: ...
    async def list_available_candidates(self, tenant_id: UUID, variant_id: UUID, location_ids: list[UUID]) -> list[Any]: ...

    # --- Ledger ---
    async def add_ledger_entry(self, tenant_id: UUID, data: dict[str, Any]) -> Any: ...
    async def list_ledger(
        self,
        tenant_id: UUID,
        *,
        limit: int,
        cursor: tuple[datetime, UUID] | None,
        variant_id: UUID | None = None,
        location_id: UUID | None = None,
    ) -> tuple[list[Any], bool]: ...

    # --- Transfers ---
    async def get_transfer(self, tenant_id: UUID, resource_id: UUID, *, lock: bool = False) -> Any | None: ...
    async def list_transfers(
        self, tenant_id: UUID, *, limit: int, cursor: tuple[datetime, UUID] | None, status: str | None = None
    ) -> tuple[list[Any], bool]: ...
    async def create_transfer(self, tenant_id: UUID, actor_id: UUID, data: dict[str, Any]) -> Any: ...

    # --- Reservations ---
    async def get_reservation(self, tenant_id: UUID, resource_id: UUID, *, lock: bool = False) -> Any | None: ...
    async def list_reservations(
        self,
        tenant_id: UUID,
        *,
        limit: int,
        cursor: tuple[datetime, UUID] | None,
        variant_id: UUID | None = None,
        status: str | None = None,
    ) -> tuple[list[Any], bool]: ...
    async def create_reservation(self, tenant_id: UUID, actor_id: UUID, data: dict[str, Any]) -> Any: ...

    # --- Fulfillment scopes ---
    async def get_fulfillment_scope(self, tenant_id: UUID, resource_id: UUID, *, lock: bool = False) -> Any | None: ...
    async def list_fulfillment_scopes(
        self, tenant_id: UUID, *, limit: int, cursor: tuple[datetime, UUID] | None, warehouse_id: UUID | None = None
    ) -> tuple[list[Any], bool]: ...
    async def list_active_scopes_for(self, tenant_id: UUID, scope_type: str, scope_id: UUID) -> list[Any]: ...
    async def create_fulfillment_scope(self, tenant_id: UUID, actor_id: UUID, data: dict[str, Any]) -> Any: ...

    # --- Cross-references ---
    async def variant_exists(self, tenant_id: UUID, variant_id: UUID) -> bool: ...
    async def active_location_ids_for_warehouses(self, tenant_id: UUID, warehouse_ids: list[UUID]) -> list[UUID]: ...

    # --- Outbox / persistence ---
    async def add_event(self, envelope: EventEnvelope) -> None: ...
    async def flush(self) -> None: ...
