from typing import Protocol
from uuid import UUID

from app.domain.entities import Membership, Tenant, User


class IdentityRepository(Protocol):
    async def get_user_by_email(self, email: str) -> User | None: ...
    async def add_user(self, user: User) -> None: ...
    async def add_tenant(self, tenant: Tenant) -> None: ...
    async def add_membership(self, membership: Membership) -> None: ...
    async def list_tenants_for_user(self, user_id: UUID) -> list[Tenant]: ...
    async def commit(self) -> None: ...
