DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='nexus_app') THEN CREATE ROLE nexus_app LOGIN PASSWORD 'nexus_app' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS; END IF;
END $$;
GRANT CONNECT ON DATABASE nexus TO nexus_app;
GRANT USAGE, CREATE ON SCHEMA public TO nexus_app;
ALTER DEFAULT PRIVILEGES FOR ROLE nexus_migrator IN SCHEMA public GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO nexus_app;
ALTER DEFAULT PRIVILEGES FOR ROLE nexus_migrator IN SCHEMA public GRANT USAGE,SELECT ON SEQUENCES TO nexus_app;
