from typing import Any, Protocol
from uuid import UUID

from app.modules.platform.contracts.events import EventEnvelope


class PlatformRepository(Protocol):
    async def get_store(self, tenant_id: UUID, store_id: UUID, *, lock: bool = False) -> Any | None: ...
    async def get_resource(self, kind: str, tenant_id: UUID, resource_id: UUID) -> Any | None: ...
    async def list_resources(self, kind: str, tenant_id: UUID, store_id: UUID | None = None) -> list[Any]: ...
    async def count_resources(self, kind: str, tenant_id: UUID, store_id: UUID | None = None) -> int: ...
    async def add(self, value: Any) -> None: ...
    async def flush(self) -> None: ...
    async def add_scope(self, tenant_id: UUID, scope_type: str, resource_id: UUID, parent_scope_id: UUID | None) -> None: ...
    async def get_scope(self, tenant_id: UUID, scope_type: str, resource_id: UUID) -> Any | None: ...
    async def add_event(self, envelope: EventEnvelope) -> None: ...
    async def entitlement_limit(self, tenant_id: UUID, key: str) -> int: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
