\set ON_ERROR_STOP on
DO $$ BEGIN
 IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='nexus_migrator') THEN CREATE ROLE nexus_migrator LOGIN PASSWORD 'nexus_migrator' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS; END IF;
 IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='nexus_app') THEN CREATE ROLE nexus_app LOGIN PASSWORD 'nexus_app' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS; END IF;
 IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='nexus_test') THEN CREATE ROLE nexus_test LOGIN PASSWORD 'nexus_test' NOSUPERUSER CREATEDB NOCREATEROLE INHERIT NOBYPASSRLS; END IF;
END $$;
SELECT 'CREATE DATABASE nexus_test OWNER nexus_migrator' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname='nexus_test')\gexec
