from datetime import datetime
from typing import Any, Protocol
from uuid import UUID

from app.modules.platform.contracts.events import EventEnvelope


class CatalogRepository(Protocol):
    async def lock_tenant(self, tenant_id: UUID) -> None: ...
    async def entitlement_limit(self, tenant_id: UUID, key: str) -> int: ...
    async def count_products(self, tenant_id: UUID) -> int: ...
    async def count_variants(self, tenant_id: UUID, product_id: UUID) -> int: ...
    async def count_active_variants(self, tenant_id: UUID, product_id: UUID) -> int: ...
    async def get_product_type(self, tenant_id: UUID, resource_id: UUID, *, lock: bool = False) -> Any | None: ...
    async def get_brand(self, tenant_id: UUID, resource_id: UUID, *, lock: bool = False) -> Any | None: ...
    async def get_product(self, tenant_id: UUID, resource_id: UUID, *, lock: bool = False) -> Any | None: ...
    async def get_variant(self, tenant_id: UUID, resource_id: UUID, *, lock: bool = False) -> Any | None: ...
    async def get_taxonomy(self, tenant_id: UUID, resource_id: UUID, *, lock: bool = False) -> Any | None: ...
    async def get_category(self, tenant_id: UUID, resource_id: UUID, *, lock: bool = False) -> Any | None: ...
    async def get_identifier(self, tenant_id: UUID, resource_id: UUID, *, lock: bool = False) -> Any | None: ...
    async def get_store(self, tenant_id: UUID, resource_id: UUID, *, lock: bool = False) -> Any | None: ...
    async def get_store_assignment(self, tenant_id: UUID, product_id: UUID, store_id: UUID, *, lock: bool = False) -> Any | None: ...
    async def locale_enabled(self, tenant_id: UUID, locale: str) -> bool: ...
    async def list_resources(self, kind: str, tenant_id: UUID, *, limit: int, cursor: tuple[datetime, UUID] | None, status: str | None = None) -> tuple[list[Any], bool]: ...
    async def list_products(self, tenant_id: UUID, *, limit: int, cursor: tuple[datetime, UUID] | None, status: str | None, product_type_id: UUID | None, brand_id: UUID | None, store_id: UUID | None, search: str | None) -> tuple[list[Any], bool]: ...
    async def list_variants(self, tenant_id: UUID, product_id: UUID, *, limit: int, cursor: tuple[datetime, UUID] | None) -> tuple[list[Any], bool]: ...
    async def list_identifiers(self, tenant_id: UUID, variant_id: UUID) -> list[Any]: ...
    async def list_translations(self, tenant_id: UUID, product_id: UUID) -> list[Any]: ...
    async def list_seo(self, tenant_id: UUID, product_id: UUID) -> list[Any]: ...
    async def list_categories(self, tenant_id: UUID, taxonomy_id: UUID) -> list[Any]: ...
    async def list_product_categories(self, tenant_id: UUID, product_id: UUID) -> list[Any]: ...
    async def list_product_stores(self, tenant_id: UUID, product_id: UUID) -> list[Any]: ...
    async def create_product_type(self, tenant_id: UUID, actor_id: UUID, data: dict[str, Any]) -> Any: ...
    async def create_brand(self, tenant_id: UUID, actor_id: UUID, data: dict[str, Any]) -> Any: ...
    async def create_product(self, tenant_id: UUID, actor_id: UUID, data: dict[str, Any]) -> Any: ...
    async def create_variant(self, tenant_id: UUID, actor_id: UUID, data: dict[str, Any]) -> Any: ...
    async def create_identifier(self, tenant_id: UUID, data: dict[str, Any]) -> Any: ...
    async def upsert_translation(self, tenant_id: UUID, product_id: UUID, locale: str, data: dict[str, Any]) -> Any: ...
    async def upsert_seo(self, tenant_id: UUID, product_id: UUID, locale: str, data: dict[str, Any]) -> Any: ...
    async def create_taxonomy(self, tenant_id: UUID, actor_id: UUID, data: dict[str, Any]) -> Any: ...
    async def create_category(self, tenant_id: UUID, actor_id: UUID, data: dict[str, Any]) -> Any: ...
    async def add_category_closure(self, tenant_id: UUID, taxonomy_id: UUID, category_id: UUID, parent_id: UUID | None) -> None: ...
    async def move_category_closure(self, tenant_id: UUID, taxonomy_id: UUID, category_id: UUID, parent_id: UUID | None) -> None: ...
    async def category_would_cycle(self, tenant_id: UUID, taxonomy_id: UUID, category_id: UUID, parent_id: UUID) -> bool: ...
    async def replace_product_categories(self, tenant_id: UUID, product_id: UUID, assignments: list[dict[str, Any]]) -> None: ...
    async def create_store_assignment(self, tenant_id: UUID, actor_id: UUID, data: dict[str, Any]) -> Any: ...
    async def add_event(self, envelope: EventEnvelope) -> None: ...
    async def flush(self) -> None: ...

    # --- M3.1 Options and Variant Combinations ---
    async def get_option(self, tenant_id: UUID, resource_id: UUID, *, lock: bool = False) -> Any | None: ...
    async def get_option_by_code(self, tenant_id: UUID, code: str) -> Any | None: ...
    async def get_option_value(self, tenant_id: UUID, resource_id: UUID, *, lock: bool = False) -> Any | None: ...
    async def list_option_values(self, tenant_id: UUID, option_id: UUID) -> list[Any]: ...
    async def count_option_values(self, tenant_id: UUID, option_id: UUID) -> int: ...
    async def create_option(self, tenant_id: UUID, actor_id: UUID, data: dict[str, Any]) -> Any: ...
    async def create_option_value(self, tenant_id: UUID, actor_id: UUID, data: dict[str, Any]) -> Any: ...
    async def get_product_option(self, tenant_id: UUID, product_id: UUID, option_id: UUID, *, lock: bool = False) -> Any | None: ...
    async def list_product_options(self, tenant_id: UUID, product_id: UUID) -> list[Any]: ...
    async def count_product_options(self, tenant_id: UUID, product_id: UUID) -> int: ...
    async def replace_product_options(self, tenant_id: UUID, product_id: UUID, assignments: list[dict[str, Any]]) -> None: ...
    async def count_active_variants_using_option(self, tenant_id: UUID, product_id: UUID, option_id: UUID) -> int: ...
    async def count_variant_combinations(self, tenant_id: UUID, product_id: UUID) -> int: ...
    async def get_variant_by_fingerprint(self, tenant_id: UUID, product_id: UUID, fingerprint: str) -> Any | None: ...
    async def list_variant_option_values(self, tenant_id: UUID, variant_id: UUID) -> list[Any]: ...
    async def replace_variant_option_values(
        self, tenant_id: UUID, variant_id: UUID, product_id: UUID, pairs: list[dict[str, Any]]
    ) -> None: ...
    async def set_variant_fingerprint(self, tenant_id: UUID, variant_id: UUID, fingerprint: str | None) -> None: ...
    async def list_option_translations(self, tenant_id: UUID, option_id: UUID) -> list[Any]: ...
    async def upsert_option_translation(self, tenant_id: UUID, option_id: UUID, locale: str, data: dict[str, Any]) -> Any: ...
    async def list_option_value_translations(self, tenant_id: UUID, option_value_id: UUID) -> list[Any]: ...
    async def upsert_option_value_translation(
        self, tenant_id: UUID, option_value_id: UUID, locale: str, data: dict[str, Any]
    ) -> Any: ...
